### ISSUE TITLE
Ayaneo Air Plus only 1 LED

### ISSUE THREAD

**Issue by dmanlfc** [ShadowBlip/ayaneo-platform#13]
Hi, using your LED kernel module for Ayaneo devices however only the left LED is showing for the Ayaneo Air Plus (AMD 6800U) model , aka AB05-AMD.

It's not a hardware fault as both LED's work with standby & charging functions.

The same image works fine on the Ayaneo 2S.

Let me know what additional details you need.

**Comment by dmanlfc** [comment]
Note: Latest commit `1b48cb070b1fb8a0245115ebe2d29c5811ae3f67` is being used.

**Comment by pastaq** [comment]
Thanks for posting this issue. I'm aware of the issue and we're working on a fix for it.

**Comment by dmanlfc** [comment]
Thanks for the prompt response @pastaq . Let me know if I can be of help.

**Comment by pastaq** [comment]
Resolved in #17
