### ISSUE TITLE
Left LED is half the brightness of right LED.

### ISSUE THREAD

**Issue by judjdigj** [ShadowBlip/ayaneo-platform#21]
Hi!

Ayaneo Air 1s 8840u here. EC updated to v20240626. No matter what brightness I set, left LED is always half of the right LED's brightness. 

I tried to adjust the brightness. At 1% both leds were turned on. At 1-4% only right LED will be brighter and the left one stay the same. From then seems like every 1% the right LED will be brighter, and every 2% the left LED will be brighter. 

This issue happened at SteamFork, which use latest ayaneo-platform. However in Bazzite, which use a outdated version, both LED works fine.

I also tried the the [script, original reference implementation from reverse engineered the protocol](https://github.com/JustEnoughLinuxOS/distribution/blob/dev/packages/hardware/quirks/devices/AYANEO%20AIR/bin/ledcontrol), it also works fine.

I assume there's a bug in the latest ayaneo-platform driver?

**Comment by pastaq** [comment]
Thanks for reporting. I'll take a look at this.

**Comment by judjdigj** [comment]
> Thanks for reporting. I'll take a look at this.

Thanks for the reply! I also tried ChimeraOS, which is also use the latest module, it has the same issue.

**Comment by judjdigj** [comment]
fewtarius' PR fixed this issue. Confirmed at Ayaneo Air 1s.
